version: 2.1

workflows:
  test:
    jobs:
      - job-py38
      - job-py39
      - job-py310
      - job-py311
      - job-py312

jobs:
  job-py38: &job-template
    docker:
      - image: cimg/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt > /dev/null
            pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cpu

      - run:
          name: run unittest
          command: |
            . venv/bin/activate
            python -m unittest discover test

      - run:
          name: test components
          command: |
            . venv/bin/activate
            python -m test_component

      - run:
          name: test sample
          command: |
            . venv/bin/activate
#            python -m main -m lenet -r hp1 -d MNIST

      - store_artifacts:
          path: test-reports
          destination: test-reports

  job-py39:
    <<: *job-template
    docker:
      - image: cimg/python:3.9

  job-py310:
    <<: *job-template
    docker:
      - image: cimg/python:3.10

  job-py311:
    <<: *job-template
    docker:
      - image: cimg/python:3.11

  job-py312:
    <<: *job-template
    docker:
      - image: cimg/python:3.12
